name: Generate store.json

on:
  push:
    paths:
      - 'app/**'
  workflow_dispatch:

jobs:
  generate-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate store.json
        run: |
          echo "[" > store.json
          first=true

          for dir in app/*/; do
            id=$(basename "$dir")
            name=$(echo "$id" | sed -e 's/^./\U&/' -e 's/-/ /g')
            avatar_file=$(find "$dir" -iregex ".*\.\(jpg\|png\|jpeg\)" | head -n 1)
            ipk_file=$(find "$dir" -name "*.ipk" | head -n 1)

            [ -z "$ipk_file" ] && continue

            filename=$(basename "$ipk_file")
            package=$(echo "$filename" | cut -d_ -f1)
            version=$(echo "$filename" | cut -d_ -f2)
            avatar_url="https://raw.githubusercontent.com/${{ github.repository }}/main/${avatar_file}"
            ipk_url="https://raw.githubusercontent.com/${{ github.repository }}/main/${ipk_file}"

            if [ "$first" = true ]; then
              first=false
            else
              echo "," >> store.json
            fi

            cat <<EOF >> store.json
            {
              "id": "$id",
              "name": "$name",
              "package": "$package",
              "version": "$version",
              "avatar": "$avatar_url",
              "url": "$ipk_url"
           }
           EOF
          done

          echo "]" >> store.json

      - name: Commit store.json
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add store.json
          git commit -m "Auto-generate store.json"
          git push
