name: Generate store.json

on:
  push:
    paths:
      - 'app/**'
  workflow_dispatch:

jobs:
  generate-json:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # ⬅️ Required to allow pushing changes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run store.json generator script
        run: |
          chmod +x path_01.sh
          ./path_01.sh
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Commit and push store.json
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add store.json
          git diff --cached --quiet || git commit -m "Auto-generate store.json"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
